---
# yamllint disable rule:line-length

name: build

on:  # yamllint disable-line rule:truthy
  - push
  - pull_request

jobs:

  checkout:
    runs-on:
      - cloud-engineering
      - self-hosted
      - tools-low
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

  build:
    needs: checkout
    uses: GannettDigital/dms-devops-github-actions/.github/workflows/build-docker-and-upload-image.yaml@main

...
