---
# yamllint disable rule:line-length

name: sonarqube-triggered

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master

jobs:
  sonarqube_pr_scan:
    uses: GannettDigital/dms-devops-github-actions/.github/workflows/sonarqube-pr.yaml@main
    secrets: inherit

...
